-- Create database akina_db
-- Run this in SSMS

CREATE DATABASE akina_db;
USE akina_db;

CREATE TABLE admins (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  email NVARCHAR(255) UNIQUE NOT NULL,
  password_hash NVARCHAR(255) NOT NULL,
  created_at DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE contacts (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(255) NOT NULL,
  email NVARCHAR(255) NOT NULL,
  phone NVARCHAR(20),
  message NTEXT NOT NULL,
  type NVARCHAR(50) NOT NULL,
  created_at DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE donations (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  donor_name NVARCHAR(255) NOT NULL,
  donor_email NVARCHAR(255) NOT NULL,
  amount FLOAT NOT NULL,
  currency NVARCHAR(10) NOT NULL,
  message NTEXT,
  status NVARCHAR(20) NOT NULL,
  created_at DATETIME2 DEFAULT GETDATE()
);

CREATE TABLE newsletters (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  email NVARCHAR(255) NOT NULL,
  name NVARCHAR(255),
  subscribed_at DATETIME2 DEFAULT GETDATE(),
  is_active BIT DEFAULT 1
);

CREATE TABLE program_participants (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(255) NOT NULL,
  age INT NOT NULL,
  program_type NVARCHAR(255) NOT NULL,
  location NVARCHAR(255) NOT NULL,
  status NVARCHAR(20) NOT NULL,
  enrolled_at DATETIME2 DEFAULT GETDATE()
);

INSERT INTO admins (email, password_hash) VALUES
('admin@example.com', '$2b$10$2Nq4FthpHmXB/nfaWzhweeiuqyw8gpawSPauCVt5jbQKdkjCfkWkm');
