import React, { useState } from 'react';

const initialNewsArticles = [
  {
    title: 'Akina Ties Launches New Health & Hygiene Program',
    date: 'August 15, 2024',
    summary: 'We are excited to announce the launch of our new Health & Hygiene program aimed at providing medical care, cancer screening, and health support to vulnerable communities in Kisii and Nyamira counties.',
    link: '#'
  },
  {
    title: 'Successful Completion of Girlie Camp 2024',
    date: 'July 10, 2024',
    summary: 'Over 2000 girls participated in the 2024 Girlie Camp, an alternative rite of passage program that educates and empowers young girls to end Female Genital Mutilation in Kisii, Nyamira, and Migori counties.',
    link: '#'
  },
  {
    title: 'Feed a Granny Program Provides 3600+ Meals',
    date: 'June 5, 2024',
    summary: 'Our Feed a Granny program has provided over 3600 meals and 1200 Christmas hampers to abandoned elderly women, ensuring they receive food, medical care, and housing support.',
    link: '#'
  }
];

// Helper function to generate more related news articles
const generateMoreNewsArticles = (startIndex: number, count: number) => {
  const generated = [];
  for (let i = 0; i < count; i++) {
    const idx = startIndex + i + 1;
    generated.push({
      title: `Related News Article ${idx}`,
      date: new Date(Date.now() - idx * 86400000).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
      summary: `This is an autogenerated related news article number ${idx} providing more updates about Akina Ties' ongoing efforts and impact.`,
      link: '#'
    });
  }
  return generated;
};

const News: React.FC = () => {
  const [newsArticles, setNewsArticles] = useState(initialNewsArticles);
  const [newsDisplayCount, setNewsDisplayCount] = useState(3);

  const loadMoreNews = () => {
    const newArticles = generateMoreNewsArticles(newsArticles.length, 3);
    setNewsArticles([...newsArticles, ...newArticles]);
    setNewsDisplayCount(newsDisplayCount + 3);
  };

  return (
    <section className="py-20 bg-akina-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center mb-16">
          <h2 className="text-4xl font-bold text-akina-purple mb-6">Latest News & Updates</h2>
          <p className="text-xl text-akina-brown mb-8">
            Stay informed about the latest developments, events, and success stories from Akina Ties.
          </p>
          <div className="space-y-12 text-left">
            {newsArticles.slice(0, newsDisplayCount).map((article, index) => (
              <article key={index} className="border-b border-akina-brown pb-6">
                <h3 className="text-2xl font-semibold text-akina-purple mb-2">{article.title}</h3>
                <p className="text-sm text-akina-brown mb-2">{article.date}</p>
                <p className="text-akina-brown mb-2">{article.summary}</p>
                <a href={article.link} className="text-akina-orange hover:underline">
                  Read more
                </a>
              </article>
            ))}
          </div>
          {newsDisplayCount < newsArticles.length && (
            <div className="text-center mt-6">
              <button
                onClick={loadMoreNews}
                className="bg-akina-orange text-white px-6 py-3 rounded-lg font-semibold hover:bg-akina-purple transition-colors duration-200"
              >
                Load More
              </button>
            </div>
          )}
        </div>
      </div>
    </section>
  );
};

export default News;
