import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import julie from '../assets/Julie.avif';
import menstrualHygiene from '../assets/menstrual hiegene.jpg';
import birthdays from '../assets/birthdays.png';
import NewsletterSubscription from './NewsletterSubscription';

const initialNewsArticles = [
  {
    title: 'Akina Ties Launches New Health & Hygiene Program',
    date: 'August 15, 2024',
    summary: 'We are excited to announce the launch of our new Health & Hygiene program aimed at providing medical care, cancer screening, and health support to vulnerable communities in Kisii and Nyamira counties.',
    link: '#'
  },
  {
    title: 'Successful Completion of Girlie Camp 2024',
    date: 'July 10, 2024',
    summary: 'Over 2000 girls participated in the 2024 Girlie Camp, an alternative rite of passage program that educates and empowers young girls to end Female Genital Mutilation in Kisii, Nyamira, and Migori counties.',
    link: '#'
  },
  {
    title: 'Feed a Granny Program Provides 3600+ Meals',
    date: 'June 5, 2024',
    summary: 'Our Feed a Granny program has provided over 3600 meals and 1200 Christmas hampers to abandoned elderly women, ensuring they receive food, medical care, and housing support.',
    link: '#'
  }
];

// Helper function to generate more related news articles
const generateMoreNewsArticles = (startIndex: number, count: number) => {
  const generated = [];
  for (let i = 0; i < count; i++) {
    const idx = startIndex + i + 1;
    generated.push({
      title: `Related News Article ${idx}`,
      date: new Date(Date.now() - idx * 86400000).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
      summary: `This is an autogenerated related news article number ${idx} providing more updates about Akina Ties' ongoing efforts and impact.`,
      link: '#'
    });
  }
  return generated;
};

const OurStories: React.FC = () => {
  const [expandedStory, setExpandedStory] = useState<number | null>(null);
  const [newsArticles, setNewsArticles] = useState(initialNewsArticles);
  const [newsDisplayCount, setNewsDisplayCount] = useState(3);

  const stories = [
    {
      id: 1,
      title: "Supporting 'Julie' Through Her Medical Journey",
      image: julie,
      alt: "Julie receiving medical care",
      brief: "'Julie' came to us more than a decade ago. Lilian had been approached by her own brother to help a young child who lived on her psychotic mothers back borrowing money on the streets for her medication.",
      full: " As soon as Lilian met the young girl, she was touched with her plight and immediately contacted her then boss the late Lyle Burgoyne, the founder of Kenya Health who immediately sought for help to have this baby taken to Kijabe Hospital for medical attention where Julie's medical Journey started. with the help and support of grandma and pa Kate and Noel Doyle OAM. Julie underwent her first major head construction surgery at Kijabe Hospital. She underwent a hernia surgery then later on a double cleft  surgery. This enabled her to start experiencing a normal childhood and attend normal formal education which she was not able to attend before. Her medical Journey still goes on as she is on lifetime consultative medication which costs Akina $2700 a year ($225Aud per month) to purchase. She attends quarter medical review clinic to regulate her medication and also check on her wellness. This cannot be possible without your generous support. Click on the Donate button to continue keeping Julie alive and healthy. Together we change one life at a time."
    },
    {
      id: 2,
      title: "Empowering Girls Through Menstrual Hygiene",
      image: menstrualHygiene,
      alt: "Girls receiving menstrual hygiene support",
      brief: "In rural Kenya, our menstrual hygiene program provides reusable and disposable sanitary towels and changing rooms to girls in remote schools, ensuring they can attend classes without fear or embarrassment.",
      full: "In the heart of rural Kenya, where access to basic hygiene products is a luxury, our menstrual hygiene program stands as a beacon of dignity and empowerment. We provide reusable and disposable sanitary towels and dedicated changing rooms to girls in remote schools, ensuring they can attend classes without fear or embarrassment. This initiative not only addresses immediate health needs but also challenges cultural stigmas surrounding menstruation, fostering an environment where girls can thrive academically and personally. By promoting menstrual hygiene in these underserved communities, we're not just supplying products—we're building confidence, reducing absenteeism, preventing teen pregnancies, and paving the way for a generation of educated, empowered women who will be a force of change and lead their communities forward."
    },
    {
      id: 3,
      title: "Celebrating Life's Milestones: Birthdays and Beyond",
      image: birthdays,
      alt: "Children celebrating birthdays",
      brief: "Birthdays are more than just dates on a calendar; they're celebrations of survival, growth, and potential for children in our care facilities.",
      full: "Birthdays are more than just dates on a calendar; they're celebrations of survival, growth, and potential. In our care facilities, we transform these special days into moments of joy and belonging for children who have faced unimaginable hardships. From simple cakes baked with love to handmade cards and small gifts, we create memories that remind each child of their worth and the community's commitment to their future. These celebrations extend beyond birthdays, encompassing the everyday moments of learning, playing, and smiling that define childhood. By nurturing these experiences, we're helping children rebuild their sense of normalcy and hope, showing them that despite their past traumas, they are cherished and have a bright future ahead."
    }
  ];

  const loadMoreNews = () => {
    const newArticles = generateMoreNewsArticles(newsArticles.length, 3);
    setNewsArticles([...newsArticles, ...newArticles]);
    setNewsDisplayCount(newsDisplayCount + 3);
  };

  return (
    <div>
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h1 className="text-4xl font-bold mb-8 text-akina-purple">Our Stories</h1>
        <p className="mb-12 text-akina-brown text-lg">
          Read inspiring stories from the children, women, and communities we serve. Learn how your support is changing lives and creating lasting impact.
        </p>

        {/* Stories Blog Section */}
        <div className="space-y-12 mb-16">
          {stories.map((story) => (
            <article key={story.id} className="bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300">
              <div className="md:flex">
                <div className="md:w-1/3">
                  <img
                    src={story.image}
                    alt={story.alt}
                    className="w-full h-64 md:h-full object-cover"
                  />
                </div>
                <div className="md:w-2/3 p-8">
                  <h2 className="text-2xl font-bold mb-4 text-akina-purple">{story.title}</h2>
                  <p className="text-gray-700 mb-4 leading-relaxed">
                    {story.brief}
                  </p>
                  {expandedStory === story.id ? (
                    <div>
                      <p className="text-gray-700 mb-4 leading-relaxed">
                        {story.full}
                      </p>
                      <button
                        onClick={() => setExpandedStory(null)}
                        className="text-akina-orange hover:text-akina-purple font-medium transition-colors duration-200"
                      >
                        Read less
                      </button>
                      {story.id === 1 && (
                        <div className="mt-4">
                          <Link
                            to="/donate"
                            className="inline-block bg-akina-orange text-white px-6 py-3 rounded-lg font-semibold hover:bg-akina-purple transition-colors duration-200"
                          >
                            Support Julie
                          </Link>
                        </div>
                      )}
                    </div>
                  ) : (
                    <button
                      onClick={() => setExpandedStory(story.id)}
                      className="text-akina-orange hover:text-akina-purple font-medium transition-colors duration-200"
                    >
                      Read more →
                    </button>
                  )}
                </div>
              </div>
            </article>
          ))}
        </div>

        {/* Latest News & Updates */}
        <div className="mb-16">
          <h2 className="text-4xl font-bold text-akina-purple mb-6 text-center">Latest News & Updates</h2>
          <p className="text-xl text-akina-brown mb-8 text-center">
            Stay informed about the latest developments, events, and success stories from Akina Ties.
          </p>
          <div className="space-y-12 text-left">
            {newsArticles.slice(0, newsDisplayCount).map((article, index) => (
              <article key={index} className="border-b border-akina-brown pb-6">
                <h3 className="text-2xl font-semibold text-akina-purple mb-2">{article.title}</h3>
                <p className="text-sm text-akina-brown mb-2">{article.date}</p>
                <p className="text-akina-brown mb-2">{article.summary}</p>
                <a href={article.link} className="text-akina-orange hover:underline">
                  Read more
                </a>
              </article>
            ))}
          </div>
          {newsDisplayCount < newsArticles.length && (
            <div className="text-center mt-6">
              <button
                onClick={loadMoreNews}
                className="bg-akina-orange text-white px-6 py-3 rounded-lg font-semibold hover:bg-akina-purple transition-colors duration-200"
              >
                Load More
              </button>
            </div>
          )}
        </div>
      </section>

      <NewsletterSubscription />
    </div>
  );
};

export default OurStories;
